-- Khedmat push-device registry
--
-- Purpose:
-- - Register push-capable app installations against authenticated users.
-- - Support multiple devices per user.
-- - Support iOS and Android from one schema.
-- - Support Expo Push Service initially while leaving room for direct APNs/FCM
--   later if Khedmat needs it.
-- - Handle token rotation and account switching safely.
-- - Never expose another user's push token to the mobile client.
--
-- Client write model:
-- - Authenticated clients do NOT insert/update/delete this table directly.
-- - Registration happens through public.register_push_device().
-- - Logout/device disable happens through public.disable_push_device().
-- - Clients may SELECT only their own rows.
--
-- Later:
-- - The push Edge Function will use service-role access to find active tokens,
--   record delivery failures, and disable permanently invalid tokens.

create table public.push_devices (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null
    references public.profiles(id)
    on delete cascade,

  -- Stable ID generated once by the Khedmat installation and kept locally.
  -- It is NOT an advertising/device hardware identifier.
  installation_id uuid not null,

  platform text not null
    check (platform in ('ios', 'android')),

  push_provider text not null default 'expo'
    check (push_provider in ('expo', 'apns', 'fcm')),

  push_token text not null,

  -- Expo/EAS project UUID when available. Kept nullable until N9.
  project_id text,

  app_version text,

  enabled boolean not null default true,

  last_registered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  disabled_at timestamptz,
  disabled_reason text,

  delivery_failure_count integer not null default 0
    check (delivery_failure_count >= 0),

  last_delivery_error text,
  last_delivery_error_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (pg_catalog.btrim(push_token) <> ''),

  check (
    project_id is null
    or pg_catalog.btrim(project_id) <> ''
  ),

  check (
    app_version is null
    or pg_catalog.btrim(app_version) <> ''
  ),

  check (
    disabled_reason is null
    or pg_catalog.btrim(disabled_reason) <> ''
  ),

  check (
    (
      enabled = true
      and disabled_at is null
    )
    or
    enabled = false
  )
);

comment on table public.push_devices is
  'Push-capable Khedmat app installations. Client registration is controlled through security-definer RPCs.';

comment on column public.push_devices.user_id is
  'Authenticated Supabase user currently associated with this push installation.';

comment on column public.push_devices.installation_id is
  'Random app-installation UUID generated by Khedmat; not a hardware or advertising identifier.';

comment on column public.push_devices.push_provider is
  'Push token namespace: Expo initially; APNs/FCM reserved for future direct delivery.';

comment on column public.push_devices.push_token is
  'Push delivery token. Sensitive routing data; never readable by other users.';


-- ---------------------------------------------------------------------------
-- Metadata
-- ---------------------------------------------------------------------------

create or replace function public.set_push_device_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

create trigger set_push_devices_updated_at
before update on public.push_devices
for each row
execute function public.set_push_device_updated_at();


-- ---------------------------------------------------------------------------
-- Uniqueness / indexes
-- ---------------------------------------------------------------------------

-- A provider/token identifies one active push endpoint globally.
--
-- This also makes account switching deterministic: register_push_device()
-- transfers ownership of an already-known token to the currently
-- authenticated account instead of allowing the same active token to point
-- at two users.
create unique index push_devices_provider_token_uidx
on public.push_devices (
  push_provider,
  push_token
);

-- A single app installation may have only one ACTIVE registration for a user.
-- Historical disabled registrations remain available for diagnostics.
create unique index push_devices_active_user_installation_uidx
on public.push_devices (
  user_id,
  installation_id
)
where enabled = true;

create index push_devices_active_user_idx
on public.push_devices (
  user_id,
  platform,
  last_seen_at desc
)
where enabled = true;

create index push_devices_installation_idx
on public.push_devices (
  installation_id
);


-- ---------------------------------------------------------------------------
-- Registration RPC
-- ---------------------------------------------------------------------------

create or replace function public.register_push_device(
  p_installation_id uuid,
  p_platform text,
  p_push_provider text,
  p_push_token text,
  p_project_id text default null,
  p_app_version text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_device_id uuid;
  v_platform text := pg_catalog.lower(
    pg_catalog.btrim(
      coalesce(p_platform, '')
    )
  );
  v_push_provider text := pg_catalog.lower(
    pg_catalog.btrim(
      coalesce(p_push_provider, '')
    )
  );
  v_push_token text := pg_catalog.btrim(
    coalesce(p_push_token, '')
  );
  v_project_id text := nullif(
    pg_catalog.btrim(
      coalesce(p_project_id, '')
    ),
    ''
  );
  v_app_version text := nullif(
    pg_catalog.btrim(
      coalesce(p_app_version, '')
    ),
    ''
  );
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_installation_id is null then
    raise exception 'An installation ID is required.';
  end if;

  if v_platform not in ('ios', 'android') then
    raise exception 'Unsupported push platform.';
  end if;

  if v_push_provider not in ('expo', 'apns', 'fcm') then
    raise exception 'Unsupported push provider.';
  end if;

  if v_push_token = '' then
    raise exception 'A push token is required.';
  end if;

  -- If this installation rotated to a new token, retain the old record for
  -- diagnostics but disable it before activating the replacement.
  update public.push_devices
  set
    enabled = false,
    disabled_at = pg_catalog.now(),
    disabled_reason = 'token-rotated',
    last_seen_at = pg_catalog.now()
  where user_id = v_user_id
    and installation_id = p_installation_id
    and enabled = true
    and (
      push_provider <> v_push_provider
      or push_token <> v_push_token
    );

  -- A push endpoint may belong to only one signed-in account at a time.
  --
  -- If the same app installation is used after signing into another Khedmat
  -- account, ownership is transferred to the current authenticated user.
  insert into public.push_devices (
    user_id,
    installation_id,
    platform,
    push_provider,
    push_token,
    project_id,
    app_version,
    enabled,
    last_registered_at,
    last_seen_at,
    disabled_at,
    disabled_reason,
    delivery_failure_count,
    last_delivery_error,
    last_delivery_error_at
  )
  values (
    v_user_id,
    p_installation_id,
    v_platform,
    v_push_provider,
    v_push_token,
    v_project_id,
    v_app_version,
    true,
    pg_catalog.now(),
    pg_catalog.now(),
    null,
    null,
    0,
    null,
    null
  )
  on conflict (push_provider, push_token)
  do update
  set
    user_id = excluded.user_id,
    installation_id = excluded.installation_id,
    platform = excluded.platform,
    project_id = excluded.project_id,
    app_version = excluded.app_version,
    enabled = true,
    last_registered_at = pg_catalog.now(),
    last_seen_at = pg_catalog.now(),
    disabled_at = null,
    disabled_reason = null,
    delivery_failure_count = 0,
    last_delivery_error = null,
    last_delivery_error_at = null
  returning id
  into v_device_id;

  return v_device_id;
end;
$$;


-- ---------------------------------------------------------------------------
-- Disable RPC
-- ---------------------------------------------------------------------------

create or replace function public.disable_push_device(
  p_installation_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_updated_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_installation_id is null then
    raise exception 'An installation ID is required.';
  end if;

  update public.push_devices
  set
    enabled = false,
    disabled_at = pg_catalog.now(),
    disabled_reason = 'signed-out',
    last_seen_at = pg_catalog.now()
  where user_id = v_user_id
    and installation_id = p_installation_id
    and enabled = true;

  get diagnostics v_updated_count = row_count;

  return v_updated_count > 0;
end;
$$;


-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public.push_devices enable row level security;

create policy "Users can read their own push devices"
on public.push_devices
for select
to authenticated
using (
  user_id = (select auth.uid())
);


-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------

-- No direct client mutation of push-device records.
revoke all
on table public.push_devices
from anon, authenticated;

grant select
on table public.push_devices
to authenticated;

grant all
on table public.push_devices
to service_role;

-- Registration/disable RPCs are the only authenticated mutation surface.
revoke execute
on function public.register_push_device(
  uuid,
  text,
  text,
  text,
  text,
  text
)
from public, anon;

grant execute
on function public.register_push_device(
  uuid,
  text,
  text,
  text,
  text,
  text
)
to authenticated;

revoke execute
on function public.disable_push_device(uuid)
from public, anon;

grant execute
on function public.disable_push_device(uuid)
to authenticated;

-- Trigger helper is internal-only.
revoke execute
on function public.set_push_device_updated_at()
from public, anon, authenticated;
